apiVersion: v1
kind: Service
metadata:
  name: edge-microgateway
  labels:
    app: edge-microgateway 
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: edge-microgatewy 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge-microgateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: edge-microgateway
    spec:
      containers:
        - name: edge-microgateway
          image: gcr.io/project/microgateway
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
---
